### ISSUE TITLE
[gazebo-8] process has died

### ISSUE THREAD

**Issue by qycqycqyc** [hakuturu583/ros_ship_packages#13]
Would you mind tell me how to fix it?
[gazebo-8] process has died [pid 23357, exit code 134, cmd /opt/ros/kinetic/lib/gazebo_ros/gzserver -e ode /home/just/catkinship1_ws/src/ros_ship_packages-master/ros_ship_description/world/open_water.world __name:=gazebo __log:=/home/just/.ros/log/3d69d356-2f6e-11ea-9aff-7cb27d913d36/gazebo-8.log].
log file: /home/just/.ros/log/3d69d356-2f6e-11ea-9aff-7cb27d913d36/gazebo-8*.log

**Comment by Harvey2019** [comment]
hello! i meet the same problem, have you solved it ?

**Comment by qycqycqyc** [comment]
@Harvey2019  I am sorry that I see your question so late because I had closed it before.Yes,I solved it before.Maybe you can update gazebo version and install its dependencies to fix it.
