### ISSUE TITLE
Cannot find "controller_managerConfig.Cmake" upon building package

### ISSUE THREAD

**Issue by andelnegro6** [hakuturu583/ros_ship_packages#5]
Fill-out only one section depending on whether you are reporting a bug or a new feature.

# Bug
Update here. I managed to install all the required packages. However, there is a problem with the build. I run catkin_make and it gives me a Cmake error. This one: 

> CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
>   Could not find a package configuration file provided by
>   "controller_manager" with any of the following names:
> 
>     controller_managerConfig.cmake
>     controller_manager-config.cmake

Do you know where in your package I can add these prefixes to CMAKE_PREFIX_PATH, or do you have that file at all? or is it from another dev package? 

Let me know :) thank you very much

## Specifications

  - Ubuntu version: Xenial 16.04
  - ROS Version: Kinetic

**Comment by hakuturu583** [comment]
@andelnegro6 Sorry, I will add controller manager to package.xml soon.

**Comment by andelnegro6** [comment]
Thank you! I'll be waiting.
