### ISSUE TITLE
[ERROR] [1520304431.162725, 0.000000]: Failed to load joint_state_controller

### ISSUE THREAD

**Issue by matebearyuan** [hakuturu583/ros_ship_packages#7]
Everything seems to be built successfully. When I ran the command "roslaunch ros_ship_gazebo_plugins wam-v_gazebo.launch", the ship could not be controlled. The errors can be found in the terminal like the following, can you give me some helpful suggestion? Thanks very much!

[ERROR] [1520304431.162725, 0.000000]: Failed to load joint_state_controller
[INFO] [1520304431.163007, 0.000000]: Loading controller: right_motor_controller
[ERROR] [1520304431.164591474]: Could not load controller 'right_motor_controller' because controller type 'velocity_controllers/JointVelocityController' does not exist.
[ERROR] [1520304431.164627068]: Use 'rosservice call controller_manager/list_controller_types' to get the available types
[ERROR] [1520304432.165761, 0.000000]: Failed to load right_motor_controller
[INFO] [1520304432.166032, 0.000000]: Loading controller: left_motor_controller
[ERROR] [1520304432.167711935]: Could not load controller 'left_motor_controller' because controller type 'velocity_controllers/JointVelocityController' does not exist.
[ERROR] [1520304432.167750789]: Use 'rosservice call controller_manager/list_controller_types' to get the available types
[ERROR] [1520304433.168274, 0.000000]: Failed to load left_motor_controller

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Ubuntu version: 16.04
  - ROS Version: kinetic
  - Branch:

**Comment by RyodoTanaka** [comment]
@matebearyuan 
It seems like, `velocity_controllers` package is not installed.
To fix this, just install with apt.
```bash
$ sudo apt install ros-kinetic-velocity-controllers
```

But, this error should be avoided with `rosdep` command.
If you did not do following command, you need it.
```bash
$ cd <catkin_ws>
$ rosdep install -i -y -r --from-paths src
```
After above `rosdep` command, if you still have an execution error, that means we mistake a dependency.
That should be fixed.
